### ISSUE TITLE
Refactor the code so that issue 7 and issue 8 can be addressed

### ISSUE THREAD

**Issue by balaji-s** [shrayasr/TheHexBot#9]
Right now, all the logic is written in a single class. Move the business logic and models to separate classes so that below issues can be well addressed

[issue 8](https://github.com/shrayasr/TheHexBot/issues/8)[ issue 7](https://github.com/shrayasr/TheHexBot/issues/7)

Thanks
Balaji

**Comment by shrayasr** [comment]
Let's track this in the PR directly. Thanks :)
